#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vim="nvim"
alias python="python3"
alias pip="pip3"

case `uname` in
	Darwin)
		source $HOME/opt/anaconda3/etc/profile.d/conda.sh
		;;
	Linux)
		;;
esac

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
